"""update table phone_number

Revision ID: 11f9339feb7b
Revises: 5dd522dfbb07
Create Date: 2025-03-14 10:27:58.159739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f9339feb7b'
down_revision: Union[str, None] = '5dd522dfbb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('installation_fee', sa.Float(), nullable=True))
    op.add_column('phone_numbers', sa.Column('maintenance_fee', sa.Float(), nullable=True))
    op.add_column('phone_numbers', sa.Column('vanity_number_fee', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_numbers', 'vanity_number_fee')
    op.drop_column('phone_numbers', 'maintenance_fee')
    op.drop_column('phone_numbers', 'installation_fee')
    # ### end Alembic commands ###
