"""Update table booking history, add column contract_code, user_name_release

Revision ID: 791dcd70084a
Revises: 87ef48b73f6e
Create Date: 2025-03-28 10:23:35.715535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791dcd70084a'
down_revision: Union[str, None] = '87ef48b73f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_history', sa.Column('contract_code', sa.String(length=255), nullable=True))
    op.add_column('booking_history', sa.Column('user_name_release', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_history', 'user_name_release')
    op.drop_column('booking_history', 'contract_code')
    # ### end Alembic commands ###
