"""Create table backcupDB

Revision ID: 79f80a2c6fce
Revises: 791dcd70084a
Create Date: 2025-03-31 10:13:11.484239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f80a2c6fce'
down_revision: Union[str, None] = '791dcd70084a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('type_number_name', sa.String(length=255), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('booked_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deployment_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('create_phone_number_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('name_book', sa.String(length=255), nullable=False),
    sa.Column('name_release', sa.String(length=255), nullable=True),
    sa.Column('installation_fee', sa.Integer(), nullable=True),
    sa.Column('maintenance_fee', sa.Integer(), nullable=True),
    sa.Column('vanity_number_fee', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_data_id'), 'backup_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backup_data_id'), table_name='backup_data')
    op.drop_table('backup_data')
    # ### end Alembic commands ###
