"""Add update booking_expiration in TypeNumber to notnull 

Revision ID: 87ef48b73f6e
Revises: dd42b5040d83
Create Date: 2025-03-17 17:19:34.824372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87ef48b73f6e'
down_revision: Union[str, None] = 'dd42b5040d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('type_numbers', 'booking_expiration',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('type_numbers', 'booking_expiration',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
