"""Create table

Revision ID: 92786afcc225
Revises: 2eb0e3645136
Create Date: 2025-03-13 18:36:03.217181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92786afcc225'
down_revision: Union[str, None] = '2eb0e3645136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_history', sa.Column('active', sa.Integer(), nullable=True))
    op.add_column('phone_numbers', sa.Column('active', sa.Integer(), nullable=True))
    op.add_column('providers', sa.Column('active', sa.Integer(), nullable=True))
    op.add_column('type_numbers', sa.Column('active', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_numbers', 'active')
    op.drop_column('providers', 'active')
    op.drop_column('phone_numbers', 'active')
    op.drop_column('booking_history', 'active')
    # ### end Alembic commands ###
