"""Add booking_expiration to TypeNumber

Revision ID: dd42b5040d83
Revises: 11f9339feb7b
Create Date: 2025-03-17 17:10:33.740180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd42b5040d83'
down_revision: Union[str, None] = '11f9339feb7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('type_numbers', sa.Column('booking_expiration', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('type_numbers', 'booking_expiration')
    # ### end Alembic commands ###
